# Copyright 2025 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception


# This CI runs the following:
#
# 1. proxy with untuned boo and native pytorch
# 2. prod with untuned boo and native pytorch
# 3. gemms with untuned boo and native pytorch

name: CI - Boo on RDNA4

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner to use for the job'
        required: false
        default: 'shark-mkm-1-for-boo'
        type: choice
        options:
          - shark-mkm-1-for-boo
          - shark41-rdna4
  schedule:
    - cron: "54 11 * * *"

permissions:
  contents: write

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test_boo_rdna4:
    if: ${{ github.repository_owner == 'nod-ai' || github.event_name != 'schedule' }}
    timeout-minutes: 270
    name: "Boo on RDNA 4"
    strategy:
      matrix:
        version: [3.12]
      fail-fast: false
    runs-on: ${{ github.event.inputs.runner || 'shark-mkm-1-for-boo' }}
    defaults:
      run:
        shell: bash
    env:
      VENV_DIR: ${{ github.workspace }}/.venv
      OFFLINE_SERVING: DISABLED
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: "Setting up Python"
      id: setup_python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: ${{matrix.version}}

    - name: Create Python venv
      run: |
        python -m venv ${VENV_DIR}
        source ${VENV_DIR}/bin/activate

    - name: Install pip deps
      run: |
        mkdir -p output_artifacts
        source ${VENV_DIR}/bin/activate
        pip install --index-url https://rocm.nightlies.amd.com/v2/gfx120X-all/ torch==2.9.1+rocm7.12.0a20260208
        pip install "git+https://github.com/iree-org/iree-turbine.git"
        pip install -f https://iree.dev/pip-release-links.html --upgrade --pre iree-base-compiler iree-base-runtime
        pip freeze  > $(pwd)/output_artifacts/version.txt

    - name: Download config files
      run: |
       echo "Getting config files"
       git clone --filter=blob:none --no-checkout https://x-access-token:${{ secrets.AMD_SHARK_AI_GITHUB_TOKEN }}@github.com/nod-ai/amd-shark-ai-reports.git
       cd amd-shark-ai-reports
       git sparse-checkout init --cone
       git sparse-checkout set boo/all_proxy_config.txt boo/prod_conv_config.txt boo/gemm_config.txt boo/hipblaslt-bench.sh boo/all_proxy_config_nchw.txt boo/prod_conv_config_nchw.txt boo/batch_norm_config.txt
       git checkout main
       cd -

    - name: Run hipblaslt-bench
      run: |
        source ${VENV_DIR}/bin/activate
        tarFileName=$( aws s3 ls s3://therock-nightly-tarball/ --recursive --no-sign-request | grep '\.tar\.gz$' | grep linux-gfx120X | sort -r | head -1 |  awk '{print $NF}' || true )
        echo "Installing $tarFileName"
        wget https://therock-nightly-tarball.s3.us-east-2.amazonaws.com/${tarFileName}
        mkdir install
        tar -xf *.tar.gz -C install
        export PATH=$PWD/install/bin:$PATH

        echo "============= Running Gemm Shape with hipblaslt =============================="
        bash amd-shark-ai-reports/boo/hipblaslt-bench.sh >& output_artifacts/rdna4_gemm_hipBlaslt-bench.csv

    - name: Run all proxy config
      run: |
       source ${VENV_DIR}/bin/activate
       pip freeze
       export MIOPEN_FIND_ENFORCE=3
       export PYTHONUNBUFFERED=1
       export ROCR_VISIBLE_DEVICES="0"

       echo "============ 1. Running Prod Conv shape with MIOpen and IREE without tuning ==================="
       iree-boo-driver \
            --commands-file amd-shark-ai-reports/boo/prod_conv_config.txt --csv output_artifacts/rdna4_prod_conv_miopen_iree.csv \
            --backend=torch --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 || true

       echo "============ 2. Running All proxy shape with MIOpen and IREE without tuning ==================="
       ## temporarily disable --backend=torch
       iree-boo-driver \
            --commands-file amd-shark-ai-reports/boo/all_proxy_config.txt --csv output_artifacts/rdna4_all_proxy_miopen_iree.csv \
            --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 || true

       echo "============ 3. Running Gemm shape with MIOpen and IREE without tuning ======================================="
       iree-boo-driver \
            --commands-file amd-shark-ai-reports/boo/gemm_config.txt --csv output_artifacts/rdna4_gemm_miopen_iree.csv \
            --backend=torch --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 || true

       echo "============ 4. Running Batch norm shape with MIOpen and IREE without tuning ======================================="
         iree-boo-driver \
              --commands-file amd-shark-ai-reports/boo/batch_norm_config.txt --csv output_artifacts/rdna4_batch_norm_miopen_iree.csv \
              --backend=torch --backend=iree_boo_experimental --backend=inductor --verify-numerics --numerics-reference-dtype=float32 || true

       # echo "============ 5. Running Prod Conv shape with NCHW layout with MIOpen and IREE without tuning ==================="
       # iree-boo-driver \
       #      --commands-file amd-shark-ai-reports/boo/prod_conv_config_nchw.txt --csv output_artifacts/rdna4_prod_conv_miopen_iree_nchw.csv \
       #      --backend=torch --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 || true

       # echo "============ 6. Running All proxy shape with NCHW layout with MIOpen and IREE without tuning ==================="
       # iree-boo-driver \
       #      --commands-file amd-shark-ai-reports/boo/all_proxy_config_nchw.txt --csv output_artifacts/rdna4_all_proxy_miopen_iree_nchw.csv \
       #      --backend=torch --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 || true

    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
      with:
        name: rdna-boo-logs
        path: |
          output_artifacts/*.csv
          output_artifacts/version.txt

  # New job to push logs to amd-shark-ai-reports repository
  push_logs:
    name: "Push log for conv run"
    needs: [ test_boo_rdna4 ]
    if: always()
    runs-on: ubuntu-24.04
    steps:
    - name: Download log artifacts
      uses: actions/download-artifact@v7
      with:
        name: rdna-boo-logs
        path: logs

    - name: Checkout Target Repo
      if: always()
      uses: actions/checkout@v6
      with:
        repository: nod-ai/amd-shark-ai-reports
        token: ${{ secrets.AMD_SHARK_AI_GITHUB_TOKEN }}
        path: amd-shark-ai-reports

    - name: Setup reports
      if: always()
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email ""
        if [ "${{ github.event_name }}" = "schedule" ]; then
          date=$(date -u +'%Y-%m-%d')
          OUTPUT_DIR="amd-shark-ai-reports/boo/boo-nightly-gfx120X/$date/"
        else
          date="$(date -u +'%Y-%m-%d_%H-%M')"
          OUTPUT_DIR="amd-shark-ai-reports/boo/boo-custom-runs-gfx120X/${date}/"
        fi
        mkdir -p $OUTPUT_DIR
        echo "OUTPUT_DIR=$OUTPUT_DIR" >> $GITHUB_ENV

    - name: Push artifacts
      if: always()
      run: |
        cp -v logs/*.csv $OUTPUT_DIR || true
        cp -v logs/version.txt $OUTPUT_DIR
        cd amd-shark-ai-reports/boo
        git pull
        git add .
        git commit -m "Add conv report on $(date -u +'%Y-%m-%d')"
        git push origin main
        rm -rf ../logs
